![logo](/images/logoUCB.png)
# Licence L2, Université  Lyon 1 
# [Statistiques pour l'informatique]

## Consignes pour les étudiants

1. **Exécution**

**Exécuter toujours tout le notebook depuis le début** (en appuyant sur le bouton **`Executer`** ou **Run**). En effet un notebook est un programme et pas une simple page HTML qui doit s'exécuter dans l'ordre du début à la fin.

2. **En cas de problème**
Tout d'abord, redémarrez le noyau (dans la barre de menus, sélectionnez **`Noyau -> Redémarer`** ou  **`Kernel -> Restart`**),
puis exécutez toutes les cellules (dans la barre de menus, sélectionnez **`Cellule -> Executer tout`** ou **`Cellule -> Run All`**).

In [1]:
from validation.validation import info_etudiant
NOM, PRENOM, NUMERO_ETUDIANT = info_etudiant()
print("Etudiant {} {}  id={}".format(NOM,PRENOM,NUMERO_ETUDIANT))

ModuleNotFoundError: No module named 'validation'

<hr>

# Fonctionnement des Travaux Pratiques

Compléter le code après la ligne <code> # YOUR CODE GOES HERE </code>.  
Une fois votre code écrit, supprimer la ligne <code> raise NotImplementedError() </code> avant d'exécuter.

Lien vers le cours : [site](https://licence-math.univ-lyon1.fr/doku.php?id=a23:s3_stats_pour_info:page)

Dans les cellules suivantes une explication des tests est donnée:

In [2]:
print("je suis ici  and i am happy")

je suis ici  and i am happy


Qui a gagné le tour de France de 2023 ?
- 'A': Jonas Vingegaard 
- 'B': Tadej Pogačar 
- 'C': Thibaut Pinot 

Quand la réponse est juste, aucun message d'erreur ne s'affiche.

In [2]:
ReponseQuestionTest = 'A'
assert(ReponseQuestionTest=='A')

Quand la réponse est fausse, un message d'erreur s'affiche.

In [3]:
ReponseQuestionTest = 'B'
assert(ReponseQuestionTest=='A')

AssertionError: 

<div class="alert alert-block alert-danger">
<b>Attention:</b> Il faut répondre 'A' ou 'B' ou 'C'.</div>

In [ ]:
ReponseQuestionTest = A
assert(ReponseQuestionTest=='A')

<hr>

# Exercice 1 : Quelques notions de base de python

1. Boucle *for* : Que font les codes suivants :

* Code 1 :
<p style="background:#F3F3F3;" >
<code style="background:#F3F3F3;">for i in [0,1,2,3]:
    print(i) </code> </p>  


* Code 2 : 
<p style="background:#F3F3F3;" >
<code style="background:#F3F3F3;">for j in range(4):
    print(j) </code> </p>


*Attention l'indentation peut s'avérer erronée lors de la copie, si le* <code> print </code> *n'apparait pas en vert corriger.* 
    
    

In [19]:
# Question 1 :
# YOUR CODE HERE
for i in [0,1,2,3]:
  print(i) 
## that's similaire

for j in range(4):
  print(j)


0
1
2
3
0
1
2
3


2. Condition *if* : Que fait le code suivant:

<p style="background:#F3F3F3">
<code style="background:#F3F3F3;"># Code à recopier
a= 8
if a>4:
    print("a est plus grand que 4")
else:
    print("a est plus petit ou egal a 4")</code> </p>

In [20]:
# Question 2

# YOUR CODE HERE
a= 8
if a>4:
    print("a est plus grand que 4")
else:
    print("a est plus petit ou egal a 4")


a est plus grand que 4


3. *Indentation* :  Python utilise l’indentation pour comprendre la fin des boucles, conditions, fonctions...   
Tester le code suivant, et corriger l’erreur.

<p style="background:#F3F3F3;margin-left: -0.5em;" ><code style="background:#F3F3F3;"># Code à recopier
for i in range(10):
if not i==4:
print(i)</code> </p>

In [21]:
# Question 3

# YOUR CODE HERE
for i in range(10):
    if not i==4:
        print(i)


0
1
2
3
5
6
7
8
9


4. *Aide*: Lorsque vous cherchez comment utiliser une fonction, penser à chercher dans l’aide et sur
internet.

In [10]:
s = sum(1,2,3,4) #souleve une erreur

TypeError: sum() takes at most 2 arguments (4 given)

In [11]:
help(sum)  # il lui faut un "iterable" par exemple une liste

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [12]:
s = sum([1,2,3,4])
print(s)

10


5. *Variables aléatoires*: Comprendre et expliquer le code suivant (utiliser toutes les ressources d’aide
nécessaire pour comprendre ce que font les fonctions) :

<p style="background:#F3F3F3">
<code style="background:#F3F3F3;"># Code à recopier 1
b = np.random.binomial(1,1/2,30)
print(b) </code> </p>

<p style="background:#F3F3F3">
<code style="background:#F3F3F3;"># Code à recopier 2
b = np.random.binomial(1,1/2,30)
print(b)
# Pourquoi est-ce différent de la première fois ?</code> </p>

<p style="background:#F3F3F3">
<code style="background:#F3F3F3;"># Code à recopier 3
m = np.random.binomial(1,1/2,(4,3))
print(m) </code> </p>

In [32]:
# Question 5

# YOUR CODE HERE
b = np.random.binomial(1,1/2,30)
print(b) 
b = np.random.binomial(1,1/2,30)
print(b)
print("\n")
t = np.random.binomial(30,1/2)
print(t)
print("\n")
m = np.random.binomial(1,1/2,(4,3))
print(m) 
#code Adam Aysoy 

n = 10
p = 0.3
size = 5  # Vous pouvez spécifier la taille de l'échantillon que vous voulez

echantillon = np.random.binomial(n, p, size)
print(echantillon)



[0 1 1 1 0 0 1 1 1 0 0 0 1 0 1 0 1 0 0 0 0 1 1 1 0 1 1 0 0 1]
[0 0 1 0 1 0 1 0 0 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 1 0 0 1 1 0]


13


[[1 0 1]
 [0 1 1]
 [1 0 1]
 [0 1 0]]
[3 3 2 1 6]


# Exercice 2 : NumPy

Pour utiliser la bibliothèque *NumPy* il est généralement nécessaire de l'importer :

In [ ]:
import numpy as np

1. Commandes de base

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
b = np.cos(1); print("b = %s" % b)
bb = np.sqrt(4); print("bb = %s" % bb) 
 </code> </p>

In [26]:
# Question 1

# YOUR CODE HERE
b = np.cos(1); print("b = %s" % b)
bb = np.sqrt(4); print("bb = %s" % bb) 

# Aysoy code 


angle_en_radians = 0.5  # Remplacez 0.5 par l'angle en radians que vous souhaitez calculer
cos_result = np.cos(angle_en_radians)

print(cos_result)



b = 0.5403023058681398
bb = 2.0
0.8775825618903728


2. Création de tableaux NumPy

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 1
u = [1, 9, -4, 0.5]
print(2*u)
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 2
v = np.array([1, 9, -4, 0.5])
print(2*v)
print(20*"-")
print(v[2])
print(20*"-")
print(v[0])
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 3
print(v.size)
print(20*"-")
print(np.size(v))
print(20*"-")
print(v.shape)
# la numérotation commence à zero
</code> </p>

In [35]:
# Question 2 

# YOUR CODE HERE
u = [1, 9, -4, 0.5]
print(2*u)
v = np.array([1, 9, -4, 0.5])
print(2*v)
print(20*"-")
print(v[2])
print(20*"-")
print(v[0])

print(v.size)
print(20*"-")
print(np.size(v))
print(20*"-")
print(v.shape)

[1, 9, -4, 0.5, 1, 9, -4, 0.5]
[ 2. 18. -8.  1.]
--------------------
-4.0
--------------------
1.0
4
--------------------
4
--------------------
(4,)


3. Intervalles et répétitions

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 1
print(np.linspace(0, 2 * np.pi, 10))
print(20*"-")
print(np.linspace(20, 1, 10))
print(20*"-")
x,dx=np.linspace(0,6.3,10,retstep=True)
print(x)
print(20*"-")
print(dx)
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 2
x = np.arange(0, 10, 0.5)
print(x)
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 3
dx = 0.5
x = np.arange(0, 10+dx/2, dx)
print(x)
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 4
y = np.arange(10, -dx/2, -dx)
print(y)
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 5
print(np.repeat(3.2, 4))
print(20*"-")
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))
print(20*"-")
print(np.repeat(x, 3, axis=1))
print(20*"-")
print(np.repeat(x, 4, axis=0))
</code> </p>

In [42]:
# Question 4

# YOUR CODE HERE
print(np.linspace(0, 2 * np.pi, 10))
print(20*"-")
print(np.linspace(20, 1, 10))
print(20*"-")
x,dx=np.linspace(0,6.3,10,retstep=True)
print(x)
print(20*"-")
print(dx)
y = np.arange(10, -dx/2, -dx)
print(y)
print(np.repeat(3.2, 4))
print(20*"-")
x = np.array([[1,2],[3,4]])
print(np.repeat(x, 2))
print(20*"-")
print(np.repeat(x, 3, axis=1))
print(20*"-")
print(np.repeat(x, 4, axis=0))
print("\n")
print("code Hana Adam")
#code Adam Aysoy
# hini da code haggui 

valeurs = np.linspace(0, 1, 10)

print(valeurs)


[0.         0.6981317  1.3962634  2.0943951  2.7925268  3.4906585
 4.1887902  4.88692191 5.58505361 6.28318531]
--------------------
[20.         17.88888889 15.77777778 13.66666667 11.55555556  9.44444444
  7.33333333  5.22222222  3.11111111  1.        ]
--------------------
[0.  0.7 1.4 2.1 2.8 3.5 4.2 4.9 5.6 6.3]
--------------------
0.7
[10.   9.3  8.6  7.9  7.2  6.5  5.8  5.1  4.4  3.7  3.   2.3  1.6  0.9
  0.2]
[3.2 3.2 3.2 3.2]
--------------------
[1 1 2 2 3 3 4 4]
--------------------
[[1 1 1 2 2 2]
 [3 3 3 4 4 4]]
--------------------
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]
 [3 4]]


code Hana Adam
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


4. Opérations sur les vecteurs

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
A = np.array([1, 2, 3, 6])
B = np.array([0, -4, 9, 4]);
print(np.exp(A))
print(20*"-")
print(A+B)
print(20*"-")
print(A*B)
print(20*"-")
print(A/B)
print(20*"-")
print(2*A)
print(20*"-")
print(A+1)
print(20*"-")
print(A+np.array([1,2,3]))
</code> </p>

In [49]:
# Question 4

# YOUR CODE HERE
A = np.array([1, 2, 3, 6])
B = np.array([0, -4, 9, 4])
print(np.exp(A))
print(20*"-")
print(A+B)
print(20*"-")
print(A*B)
print(20*"-")
print(A/B)
print(20*"-")
print(2*A)
print(20*"-")
print(A+1)
print(20*"-")
print(A+np.array([1,2,3]))




#test Adam Aysoy code 
#je voulais retouver sur le serveur 
print("\n")
print("ici ")
A = np.array([10, 20, 30, 40])
result = A + np.array([1, 2, 3, 4])
print(result)


[  2.71828183   7.3890561   20.08553692 403.42879349]
--------------------
[ 1 -2 12 10]
--------------------
[ 0 -8 27 24]
--------------------
[        inf -0.5         0.33333333  1.5       ]
--------------------
[ 2  4  6 12]
--------------------
[2 3 4 7]
--------------------


/tmp/ipykernel_898018/95674608.py:12: RuntimeWarning: divide by zero encountered in divide
  print(A/B)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

5. Sélection

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
print(A==2)
print(20*"-")
print(A[A>2])
</code> </p>

In [ ]:
# Question 5

# YOUR CODE HERE
raise NotImplementedError()

6. Sommes et sommes cumulées

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
u = np.arange(1,10,1)
print(np.sum(u))
print(20*"-")
print(np.cumsum(u))
</code> </p>

In [ ]:
# Question 5

# YOUR CODE HERE
raise NotImplementedError()

7. Création et opération sur les matrices     
Repérez les éventuels problèmes:

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
A.shape = (2,2); print(A)
print(20*"-")
print(A.transpose())
C = B.reshape(2,2).T
print(C); 
print(20*"-")
print(A @ C)
print(20*"-")
print(np.matmul(A,C))
print(20*"-")
print(C[1,])
print(20*"-")
print(C/A[1,])
</code> </p>

In [ ]:
# Question 7

# YOUR CODE HERE
raise NotImplementedError()

# Exercice 3 : Matplotlib

Pour tracer le graphique d’une fonction mathématique, on utilise la bibliothèque *matplotlib*, dont
la partie pertinent *pyplot* a été importée sous le
petit nom de *plt*.

In [ ]:
import matplotlib.pyplot as plt

1. Recopier et exécuter les codes suivants :

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 1
x = np.linspace(0, 2*np.pi, 100)
plt.plot(x, np.sin(x))
plt.show()
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 2
plt.plot(x, np.cos(x))
plt.plot(x, np.sin(x))
plt.show()
</code> </p>

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier 3
plt.plot([0, 1], [1, 0], "b",linewidth=2,linestyle='--',label='segment')
plt.plot(0.6, 0.9, "r+",label='point')
plt.xlabel("x")
plt.ylabel("y")
plt.title("joli graphe")
plt.legend()
plt.show()
</code> </p>

In [ ]:
# Question 1
# YOUR CODE HERE
raise NotImplementedError()

2. Plusieurs graphes dans la même image :

<p style="background:#F3F3F3"> <code style="background:#F3F3F3;"># Code à recopier
fig,ax=plt.subplots(1,2)
ax[0].plot(x, np.sin(x))
ax[1].plot(y, y*np.sin(y))
fig.suptitle("2 jolis graphes")
ax[0].set_title("sinus")
ax[1].set_xlabel("x")
plt.show()
</code> </p>

In [ ]:
# Question 2

# YOUR CODE HERE
raise NotImplementedError()

# Exercices supplémentaires

## Exercice 1 :  La factorielle

Ecrire une fonction qui prend un entier et retourne sa factorielle.   
On rappelle que : $n!=1 \times 2 \times ...\times (n-2) \times(n-1)\times n$.

In [ ]:
def factorielle(n):
    #....#

# YOUR CODE HERE
raise NotImplementedError()



In [ ]:
assert(factorielle(4)==24)

## Exercice 2 :  Coefficient Binômial

On rappelle la formule du coefficient binomial :

$C_{n}^k=\binom{n}{k}=\frac{n!}{k!(n - k)!}.$


In [ ]:
def coeff_binomial(k,n):
    #...#
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert(coeff_binomial(3,6)==20)

# Exercice 3 : Triangle de Pascal

Le triangle de Pascal (https://fr.wikipedia.org/wiki/Triangle_de_Pascal), contient les coefficients binomiaux. On peut le lire comme un tableau triangulaire inférieur où la case à l'intersection entre la ligne $n$ et la colonne $k$ correspond au coefficient $\binom{n-1}{k-1}$.  

On se propose dans cet exercice d'écrire une fonction qui prend en entrée un entier $n$ et qui retourne le triangle de Pascal (sous forme de tableau) à $n+1$ lignes.



In [ ]:
# Indice : utiliser une double boucle for
def triangle_pascal(n):
    tableau = np.zeros((n+1,n+1),int)
    #...#
# YOUR CODE HERE
raise NotImplementedError()
    

In [ ]:
triangle4=triangle_pascal(4)
assert(triangle4[-1,2]==6)

# Exercice 4 : Suite de Syracuse 

La suite de Syracuse est une suite récurrente d'entiers naturels définie comme suit :

$$
u_0 = N \in \mathbb{N},\;\\
u_n = 
\begin{cases}
\frac{u_{n-1}}{2},\; si \; u_{n-1}\; pair\\
3u_{n-1}+1, \; sinon.
\end{cases}
$$

On se propose d'écrire une fonction qui prend en entrée le nombre de termes à calculer $n$ et la valeur du premier terme $u_0$ et qui renvoit un vecteur contenant tous ces termes.  

Une fois la fonction écrite, il est proposé de tracer la suite pour plusieurs valeurs (que vous pouvez varier). Que pouvez-vous dire sur cette suite ?   
Pour plus d'information voir : https://fr.wikipedia.org/wiki/Conjecture_de_Syracuse.

In [ ]:
def syracuse(n,u_0):
    U_syr=np.zeros(n+1,int)
    U_syr[0]=u_0
    #...#
    # YOUR CODE HERE
    raise NotImplementedError()
        
                
        

In [ ]:
U10 = syracuse(20,11)
assert(U10[-1]==1)

In [ ]:
U_syr27 = syracuse(100,27)
U_syr12 = syracuse(100,12)
# YOUR CODE HERE
raise NotImplementedError()